blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('reports/', include('reports.urls', namespace='reports')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

 

shop/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import cart_count


app_name = 'shop'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),
    path('politica_privacidad/', views.politica_privacidad, name='politica_privacidad'),
    path('terminos_condiciones/', views.terminos_condiciones, name='terminos_condiciones'),
    path('tyc/', views.tyc, name='tyc'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search_products, name='search_products'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   



   

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class PublishedManager(models.Manager):
    def get_queryset(self):
        return (
            super().get_queryset().filter(status=Post.Status.PUBLISHED)
        )

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Borrador'
        PUBLISHED = 'PB', 'Publicado'

    title = models.CharField(max_length=250, verbose_name="Título")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts',
        verbose_name="Autor"
    )
    body = models.TextField(verbose_name="Contenido")
    publish = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Publicación")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualización")
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name="Estado"
    )
    image = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name="Imagen")  # Nuevo campo

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
        verbose_name = "Publicación"
        verbose_name_plural = "Publicaciones"

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post

def post_list(request):
    posts = Post.published.all()
    return render(
        request,
        'blog/post/list.html',
        {'posts': posts}
    )


def post_detail(request, id):
    post = get_object_or_404(
        Post,
        id=id,
        status=Post.Status.PUBLISHED
    )
    return render(
        request,
        'blog/post/detail.html',
        {'post': post}
    )

blog/templates/blog/post/detail.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');

  body {
      margin: 0;
      padding: 0;
      font-family: 'Poppins', sans-serif;
  }

  h1, h2, h3, h4, h5, h6 {
      font-family: 'Poppins', sans-serif;
  }

  .card {
      max-width: 100%; /* Asegúrate de que la card no tenga un límite de ancho */
  }
</style>

{% block content %}
<nav class="navbar navbar-expand-lg rounded" style="background-color: #34DD78; margin: 10px;">
  <div class="container-fluid" style="padding: 0;">
      <div class="btn">
          <a href="{% url 'blog:post_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="40px" fill="#4E50B4" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
              <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
            </svg>
          </a>
      </div>
      <div class="mx-auto">
          <a class="navbar-brand fw-bold me-5" href="{% url 'shop:product_list' %}" style="color: #4E50B4; font-family: 'Poppins', sans-serif;">
              <img src="{% static 'img/logo_v-pharma.png' %}" alt="logo" width="50" class="me-1">
              <span style="color: #E7F1F6;">Blog</span>.V-Pharma
          </a>
      </div>
  </div>
</nav>

<div class="container mt-4 mb-5">
  <div class="row justify-content-center">
    <div class="col-lg-12">  <!-- Cambiado a col-lg-12 para más ancho -->
      <div class="shadow-lg border-light p-3">
        {% if post.image %} 
          <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}" style="width: 100%; height: auto;">
        {% endif %}
        <div class="card-body">
          <h1 class="card-title text-center fw-bold" style="color: #9394D5;">{{ post.title }}</h1>
          <p class="card-subtitle text-muted mb-4 text-center">
            Publicado el {{ post.publish|date:"F j, Y" }} por {{ post.author }}
          </p>
          <div class="card-text p-3" style="color: #4E50B4; font-size: 20px;">
            {{ post.body|linebreaks }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="container-fluid p-4 rounded-4" style="background-color: #9394D5; width: 90%; height: 250px;">
  <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card p-4 mt-3" style="background-color: #E7F1F6; border-radius: 15px;">
            <ul class="list-unstyled">
              <li class="mb-3">
                <a href="{% static 'pdfs/ayuda-usuario.pdf' %}" style="color: #4e50b4; text-decoration: none;" class="fw-semibold">
                  <img src="{% static 'img/footer/ayuda.png' %}" alt="icon_help" width="20px"> Ayuda
                </a>
              </li>
              <li class="mb-3">
                <a href="{% url 'shop:quienes_somos' %}" style="color: #4e50b4; text-decoration: none;" class="fw-semibold">
                  <img src="{% static 'img/footer/quienes_somos.png' %}" alt="icon_quien_somos" width="20px"> Quienes somos
                </a>
              </li>
              <li class="mb-3">
                <a href="{% url 'shop:politica_privacidad' %}" style="color: #4e50b4; text-decoration: none;" class="fw-semibold">
                  <img src="{% static 'img/footer/politicas_privacidad.png' %}" alt="icon_PdP" width="20px"> Políticas de Privacidad
                </a>
              </li>
              <li class="mb-3">
                <a href="{% url 'shop:terminos_condiciones' %}" style="color: #4e50b4; text-decoration: none;" class="fw-semibold">
                  <img src="{% static 'img/footer/terminos-y-condiciones.png' %}" alt="icon_TyC" width="20px"> Términos y Condiciones
                </a>
              </li>
              <li>
                <a href="{% url 'blog:post_list' %}" style="color: #4e50b4; text-decoration: none;" class="fw-semibold">
                  <img src="{% static 'img/footer/blog.png' %}" alt="icon_blog" width="20px"> Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <h5 class="fw-bold mb-4 mt-5" style="color: #E7F1F6;">Contáctanos</h5>
          <ul class="list-unstyled">
            <li class="mb-3">
              <a style="color: white; text-decoration: none;" class="fw-semibold">
                <img src="{% static 'img/footer/whatsapp.png' %}" alt="logo_Whatsapp" width="30px">3126647917
              </a>
            </li>
            <li>
              <a href="" style="color: white; text-decoration: none;" class="fw-semibold">
                <img src="{% static 'img/footer/gmail.png' %}" alt="" width="30px"> v-pharma@gmail.com
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5 class="fw-bold mt-5 mb-4" style="color: #E7F1F6;">Síguenos</h5>
          <ul class="list-unstyled">
            <li class="mb-3">
              <a href="" style="color: white; text-decoration: none;" class="fw-semibold">
                <img src="{% static 'img/footer/facebook.png' %}" alt="logo_facebook" width="30px"> Facebook
              </a>
            </li>
            <li>
              <a href="" style="color: white; text-decoration: none;" class="fw-semibold">
                <img src="{% static 'img/footer/instagram.png' %}" alt="logo_instagram" width="30px"> Instagram
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="text-center mt-3 fw-semibold">
        <p style="color: #9394D5;">&copy; 2024 V-Pharma. Todos los derechos reservados.</p>
      </div>
  </div>
</footer>
<!-- Footer -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}v-pharma.online{% endblock %}

<style>
  .post_body {
    color: black;  /* Color normal */
    transition: color 0.3s;  /* Efecto suave al cambiar de color */
  }

  .post_body:hover {
    color: #34DD78;  /* Color al pasar el mouse */
  }
</style>

{% block content %}
<div class="container mt-4">
  <div class="m-3">
    <div class="row"> 
      <div class="col-8">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner rounded-4 mb-5">
            <div class="carousel-item active">
              <img src="{% static 'img/banner1.png' %}" class="d-block w-100" alt="banner1" style="width: 400px; height: 350px;">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/banner2.png' %}" class="d-block w-100" alt="banner2" style="width: 400px; height: 340px;">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/banner3.png' %}" class="d-block w-100" alt="banner3" style="width: 400px; height: 350px;">
            </div>
          </div>
          <button class="carousel-control-prev rounded-circle" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control">
              <svg xmlns="http://www.w3.org/2000/svg" width="40px" fill="#4E50B4" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
              </svg>
            </span>
          </button>
          <button class="carousel-control-next rounded-circle" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control">
              <svg xmlns="http://www.w3.org/2000/svg" width="40px" fill="#4E50B4" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
              </svg>
            </span>
          </button>
        </div>
      </div>
      <div class="col-4">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner rounded-4">
            <div class="carousel-item active">
              <img src="{% static 'img/banner4.png' %}" class="d-block w-100" alt="banner4" style="width: 10%; height: 350px;">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/banner5.png' %}" class="d-block w-100" alt="banner5" style="width: 10%; height: 400px;">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <h4 class="text-center mb-4 fw-bold" style="color: #4E50B4;">Publicaciones de interes</h4>
  <div id="postCarousel" class="carousel slide mb-5" data-bs-ride="carousel" data-bs-interval="2000">
    <div class="carousel-inner">
        {% for post in posts %}
            {% if forloop.first %}
                <div class="carousel-item active">
            {% else %}
                <div class="carousel-item">
            {% endif %}
                <div class="d-flex justify-content-center">
                    <div class="card shadow-lg me-3" style="width: 20rem; height: 550px;">
                        <div class="card-body text-center">
                            {% if post.image %}
                                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="rounded mb-3" style="width: 100%; height: auto;">
                            {% endif %}
                            <h5 class="card-title fw-bold" style="color: #9394D5;">{{ post.title }}</h5>
                            <a href="{% url 'blog:post_detail' post.id %}" class="post_body" style="text-decoration: none;">
                                <p class="card-text fw-semibold">{{ post.body|truncatewords:20|linebreaks }}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev rounded-circle" type="button" data-bs-target="#postCarousel" data-bs-slide="prev">
      <span class="carousel-control">
        <svg xmlns="http://www.w3.org/2000/svg" width="40px" fill="#4E50B4" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
          <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
        </svg>
      </span>
    </button>
    <button class="carousel-control-next rounded-circle" type="button" data-bs-target="#postCarousel" data-bs-slide="next">
      <span class="carousel-control">
        <svg xmlns="http://www.w3.org/2000/svg" width="40px" fill="#4E50B4" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
          <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
        </svg>
      </span>
    </button>
</div>

{% endblock %}